var settings = {
    lineColors: ['red', 'green'],
    seriesSymbol: 'triangle',
    seriesSymbolSize: 20,
    seriesLineStyleType: 'dashed',
    //seriesLineStyleColor: 'purple',
    titleShow: true,
    titleText: 'Линейный график',
    titleTextStyleColor: '#333',
    titleTextStyleFontStyle: 'italic',
    titleTextStyleFontWeight: 'bold',
    titleTextStyleFontFamily: 'sans-serif',
    titleTextStyleFontSize: '18',
    legendShow: true,
    legendTitleGap: 5,
    legendTextStyleColor: 'blue',
    legendTextStyleFontStyle: 'normal',
    legendTextStyleFontWight: 'normal',
    legendTextStyleFontFamily: 'times',
    legendTextStyleFontSize: '14',
    gridTop: '12%',
    gridLeft: '1%',
    gridRight: '10%',
    //gridBottom: '3%',
    gridContainLabel: true,
    xAxisShow: true,
    xAxisName: 'Ось Х',
    xAxisNameTextStyleColor: 'red',
    xAxisNameTextStyleFontStyle: 'normal',
    xAxisNameTextStyleFontWeight: 'bold',
    xAxisNameTextStyleFontFamily: 'times',
    xAxisNameTextStyleFontSize: '16',
    xAxisNameTextStyleAlign: 'center',
    xAxisLineStyleType: 'dotted',
    xAxisLineStyleColor: 'red',
    yAxisShow: true,
    yAxisName: 'Ось У',
    yAxisNameTextStyleColor: 'green',
    yAxisNameTextStyleFontStyle: 'normal',
    yAxisNameTextStyleFontWeight: 'bold',
    yAxisNameTextStyleFontFamily: 'times',
    yAxisNameTextStyleFontSize: '16',
    yAxisNameTextStyleAlign: 'right',
    yAxisLineStyleType: 'dotted',
    yAxisLineStyleColor: 'green'
}